# examples/configs/quickstart.yaml
defaults:
  - config


data:
  file_reader: tfxkit.common.base_utils.read_csv
  features:
    - mean radius
    - mean texture
    - mean perimeter
    - mean area
    - mean smoothness
  labels: ["target"]

  train_files: src/tfxkit/examples/train.csv
  test_files: src/tfxkit/examples/test.csv
  train_weights_column: null

model:
  parameters:
    hidden_activation: relu
    final_activation: sigmoid
    layers_list: [64, 32, 16]
    batch_norm_features: true
    batch_norm_hidden: true
    dropout: 0.8

training:
  epochs: 10
  batch_size: 32
  validation_split: 0.2


