# examples/configs/quickstart.yaml
defaults:
  - config


data:
  file_reader: tfxkit.common.base_utils.read_csv
  # xy_maker: tfxkit.common.tf_utils.xy_from_sklearn
  features:
    - mean radius
    - mean texture
    - mean perimeter
    - mean area
    - mean smoothness
  labels: ["target"]

  train_files: src/tfxkit/examples/train.csv
  test_files: src/tfxkit/examples/test.csv
  train_weights_column: null

training:
  epochs: 10
  batch_size: 32
  validation_split: 0.2


