batch_size: 8192
dropout: 0.8
ema_momentum: 0.999
features:
  - log_z
  - log_rho
  - log_length
  - log_energy
  - interaction_height
  - cos_zenith
  - pdg_map
  - log_energy_per_nucleon
  - depth
  - multiplicity
  - mu_radius_mean
  - mu_radius_std
  - mu_radius_min
  - mu_radius_max
  - mu_log_energy_mean
  - mu_log_energy_std
  - mu_log_energy_min
  - mu_log_energy_max
  - mu1_radius
  - mu2_radius
  - mu3_radius
  - mu4_radius
  - mu5_radius
  - mu6_radius
  - mu7_radius
  - mu8_radius
  - mu9_radius
  - mu10_radius
  - mu1_log_energy
  - mu2_log_energy
  - mu3_log_energy
  - mu4_log_energy
  - mu5_log_energy
  - mu6_log_energy
  - mu7_log_energy
  - mu8_log_energy
  - mu9_log_energy
  - mu10_log_energy
  - singleness
  - mu_leading_energy_fraction
  - mu_bundle_log_energy
final_layer: 4
fname_test: 
  - /data/user/navidkrad/hdf/cascades_v0.6_CscdSBU_BDT//sim/IceCube/2020/CORSIKA-in-ice/20904//test_train/test.hdf5
fname_train:
  - /data/user/navidkrad/hdf/cascades_v0.6_CscdSBU_BDT//sim/IceCube/2020/CORSIKA-in-ice/20904//test_train/train.hdf5
hidden_activation: tanh
init_layer: 192
labels:
  - CscdBDT
layer_repeat: 3
learning_rate: decay_linear
max_depth: 100
max_layers: 30
model_dir_base: /data/user/navidkrad/i3kiss/models/
model_name: v0
model_tag: CscdBDT_allfeat_w2_regu
version_tag: cascades_v0.6_CscdSBU_BDT
n_epoch: 50
optimizer: adamw
seed: 125
selection: n_photons>0
unit_step: 4
weight_decay: 0.0005
ema_overwrite_frequency: True
weights: "balanced_weights_squared"
kernel_regularizer: 1.0e-03
