batch_size: 8192
dropout: 0.8
ema_momentum: 0.999
features:
  - log_z
  - log_rho
  - log_length
  - log_energy
  - interaction_height
  - cos_zenith
  - pdg_map
  - log_energy_per_nucleon
  - depth
  - multiplicity
  - mu_radius_mean
  - mu_radius_std
  - mu_radius_min
  - mu_radius_max
  - mu_log_energy_mean
  - mu_log_energy_std
  - mu_log_energy_min
  - mu_log_energy_max
  - mu1_radius
  - mu2_radius
  - mu3_radius
  - mu4_radius
  - mu5_radius
  - mu6_radius
  - mu7_radius
  - mu8_radius
  - mu9_radius
  - mu10_radius
  - mu1_log_energy
  - mu2_log_energy
  - mu3_log_energy
  - mu4_log_energy
  - mu5_log_energy
  - mu6_log_energy
  - mu7_log_energy
  - mu8_log_energy
  - mu9_log_energy
  - mu10_log_energy
  - singleness
  - mu_leading_energy_fraction
  - mu_bundle_log_energy
  - mu1_pos_x
  - mu1_pos_y
  - mu1_pos_z
  - mu1_dir_x
  - mu1_dir_y
  - mu1_dir_z
  - mu2_pos_x
  - mu2_pos_y
  - mu2_pos_z
  - mu2_dir_x
  - mu2_dir_y
  - mu2_dir_z
  - mu3_pos_x
  - mu3_pos_y
  - mu3_pos_z
  - mu3_dir_x
  - mu3_dir_y
  - mu3_dir_z
  - mu4_pos_x
  - mu4_pos_y
  - mu4_pos_z
  - mu4_dir_x
  - mu4_dir_y
  - mu4_dir_z
  - mu5_pos_x
  - mu5_pos_y
  - mu5_pos_z
  - mu5_dir_x
  - mu5_dir_y
  - mu5_dir_z
  - mu6_pos_x
  - mu6_pos_y
  - mu6_pos_z
  - mu6_dir_x
  - mu6_dir_y
  - mu6_dir_z
  - mu7_pos_x
  - mu7_pos_y
  - mu7_pos_z
  - mu7_dir_x
  - mu7_dir_y
  - mu7_dir_z
  - mu8_pos_x
  - mu8_pos_y
  - mu8_pos_z
  - mu8_dir_x
  - mu8_dir_y
  - mu8_dir_z
  - mu9_pos_x
  - mu9_pos_y
  - mu9_pos_z
  - mu9_dir_x
  - mu9_dir_y
  - mu9_dir_z
  - mu10_pos_x
  - mu10_pos_y
  - mu10_pos_z
  - mu10_dir_x
  - mu10_dir_y
  - mu10_dir_z

final_layer: 4
fname_test:
  - /lustre/fs23/group/icecube/nrad/data/hdf/Cscd_v0.0.2_mupos/sim/IceCube/2020/CORSIKA-in-ice/20904/test_train/test.hdf5
fname_train:
  - /lustre/fs23/group/icecube/nrad/data/hdf/Cscd_v0.0.2_mupos/sim/IceCube/2020/CORSIKA-in-ice/20904/test_train/train.hdf5
hidden_activation: tanh
init_layer: 192
labels:
  - CscdBDT
layer_repeat: 3
learning_rate: decay_linear
max_depth: 100
max_layers: 30
model_name: v0.1
model_tag: newmuvars_v0.2
version_tag: Cscd_v0.0.2_mupos 
n_epoch: 50
optimizer: adamw
seed: 125
selection: n_photons>0
unit_step: 4
weight_decay: 0.0005
ema_overwrite_frequency: True
weights: "balanced_weights_squared"
kernel_regularizer: 1.0e-03
